services:
    db:
        image: postgres:16-alpine
        container_name: gastro-db
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: gastro_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d gastro_db"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: apps/backend/Dockerfile
        env_file: .env
        container_name: gastro-backend
        depends_on:
            db:
                condition: service_healthy
        environment:
            DATABASE_URL: postgres://user:password@db:5432/gastro_db
            GEMINI_API_KEY: ${GEMINI_API_KEY}
        ports:
            - "4202:4202"

    frontend:
        build:
            context: .
            dockerfile: apps/frontend/Dockerfile
            args:
                # To przekaże wartość z Twojego lokalnego .env do Dockera podczas budowania
                - BACKEND_URL=http://gastro-backend:4202
        env_file: .env
        container_name: gastro-frontend
        depends_on:
            - backend
        environment:
            # Jeśli SvelteKit ma gadać z backendem po stronie serwera:
            BACKEND_URL: http://gastro-backend:4202
        ports:
            - "5173:5173"

volumes:
    postgres_data:
